# Generated by Django 5.1.6 on 2025-02-28 19:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Mietspiegel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "wohnflaeche_qm",
                    models.DecimalField(
                        decimal_places=2, max_digits=6, verbose_name="Wohnfläche (qm)"
                    ),
                ),
                ("baujahr", models.IntegerField(verbose_name="Baujahr")),
                ("zone", models.CharField(max_length=50, verbose_name="Zone")),
                (
                    "laermbelastung",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Lärmbelastung",
                    ),
                ),
                (
                    "heizungsart",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Heizungsart"
                    ),
                ),
                (
                    "bodenbelag",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Bodenbelag"
                    ),
                ),
                (
                    "sanitaerausstattung",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Sanitärausstattung",
                    ),
                ),
                (
                    "souterrain",
                    models.BooleanField(
                        default=False, verbose_name="Wohnung im Souterrain"
                    ),
                ),
                (
                    "einfacher_kuechenboden",
                    models.BooleanField(
                        default=False, verbose_name="Einfacher Küchenboden"
                    ),
                ),
                ("aufzug", models.BooleanField(default=False, verbose_name="Aufzug")),
                (
                    "zusatzlicher_sanitarraum",
                    models.BooleanField(
                        default=False, verbose_name="Zusätzlicher Sanitärraum"
                    ),
                ),
                (
                    "maisonette",
                    models.BooleanField(default=False, verbose_name="Maisonette"),
                ),
                (
                    "einfamilienhaus",
                    models.BooleanField(default=False, verbose_name="Einfamilienhaus"),
                ),
                (
                    "sanitaerausstattung_erneuert",
                    models.BooleanField(
                        default=False, verbose_name="Sanitärausstattung erneuert"
                    ),
                ),
                (
                    "bodenbelaege_erneuert",
                    models.BooleanField(
                        default=False, verbose_name="Bodenbeläge erneuert"
                    ),
                ),
                (
                    "elektroinstallation_erneuert",
                    models.BooleanField(
                        default=False, verbose_name="Elektroinstallation erneuert"
                    ),
                ),
                (
                    "energetisch_saniert",
                    models.BooleanField(
                        default=False, verbose_name="Energetisch saniert"
                    ),
                ),
                (
                    "fussbodenheizung",
                    models.BooleanField(default=False, verbose_name="Fußbodenheizung"),
                ),
                (
                    "offene_kueche",
                    models.BooleanField(default=False, verbose_name="Offene Küche"),
                ),
                (
                    "gesamtpunktzahl",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Gesamtpunktzahl der Wohnung",
                    ),
                ),
                (
                    "rechenweg_basismiete",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="Rechenweg Basismiete (€/qm)",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, default="Mietervertrag", max_length=255
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploaded", "Uploaded"),
                            ("processing", "Processing"),
                            ("analyzed", "Analyzed"),
                        ],
                        default="uploaded",
                        max_length=20,
                    ),
                ),
                ("retention_days", models.IntegerField(default=365)),
                ("scheduled_deletion_date", models.DateField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ContractDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contract_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("address", models.TextField(blank=True, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("postal_code", models.CharField(blank=True, max_length=10, null=True)),
                ("country", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "number_of_rooms",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                ("kitchen", models.BooleanField(default=False)),
                ("bathroom", models.BooleanField(default=False)),
                ("separate_wc", models.BooleanField(default=False)),
                ("balcony_or_terrace", models.BooleanField(default=False)),
                ("garden", models.BooleanField(default=False)),
                ("garage_or_parking_space", models.BooleanField(default=False)),
                (
                    "living_space",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("year_of_construction", models.IntegerField(blank=True, null=True)),
                ("modernization", models.IntegerField(blank=True, null=True)),
                ("floor", models.IntegerField(blank=True, null=True)),
                ("elevator", models.BooleanField(default=False)),
                (
                    "energy_certificate",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "energy_consumption",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "energy_class",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("shared_facilities", models.TextField(blank=True, null=True)),
                ("keys_provided", models.TextField(blank=True, null=True)),
                ("start_date", models.DateField(blank=True, default=None, null=True)),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        default=None,
                        help_text="Leave blank for unlimited contracts",
                        null=True,
                    ),
                ),
                ("duration", models.CharField(blank=True, max_length=50, null=True)),
                ("termination_terms", models.TextField(blank=True, null=True)),
                (
                    "monthly_rent",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("additional_costs", models.TextField(blank=True, null=True)),
                (
                    "total_rent",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "heating_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("additional_clauses", models.TextField(blank=True, null=True)),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details",
                        to="contract_analysis.contract",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ContractFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_name", models.CharField(blank=True, default="", max_length=255)),
                ("file_content", models.BinaryField(null=True)),
                ("file_type", models.CharField(default="image/png", max_length=20)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("encrypted_content", models.BinaryField(null=True)),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="contract_analysis.contract",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Paragraph",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("content", models.TextField()),
                ("summary", models.TextField()),
                ("problems", models.TextField()),
                (
                    "contract_details",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paragraphs",
                        to="contract_analysis.contractdetails",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PaymentHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stripe_subscription_id", models.CharField(max_length=255)),
                ("status", models.CharField(max_length=20)),
                ("current_period_end", models.DateTimeField()),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="contract",
            index=models.Index(
                fields=["user", "status"], name="contract_an_user_id_26593c_idx"
            ),
        ),
    ]
