# Generated by Django 5.1.6 on 2025-02-28 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contract_analysis", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contractfile",
            name="file_size",
            field=models.IntegerField(default=0),
        ),
    ]
