# Generated by Django 5.1.6 on 2025-03-01 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contract_analysis", "0002_contractfile_file_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="contract",
            name="archived_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
