# Generated by Django 5.1.6 on 2025-03-07 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contract_analysis", "0002_alter_contractdetails_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contractdetails",
            name="neighborhood_description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
