# Generated by Django 5.1.6 on 2025-03-02 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contract_analysis", "0003_contract_archived_contract_archived_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="contractdetails",
            name="contract_text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
