# Generated by Django 5.1.6 on 2025-03-02 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contract_analysis", "0004_contractdetails_contract_text"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contractdetails",
            name="additional_clauses",
        ),
        migrations.AddField(
            model_name="contractdetails",
            name="additional_occupants",
            field=models.TextField(
                blank=True,
                help_text="Names of additional authorized occupants",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="contractdetails",
            name="base_rent",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="contractdetails",
            name="contract_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contractdetails",
            name="contract_version",
            field=models.CharField(
                blank=True,
                help_text="Version of the contract template used",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="contractdetails",
            name="cosmetic_repairs_responsibility",
            field=models.CharField(
                blank=True,
                help_text="Who is responsible for Schönheitsreparaturen",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="contractdetails",
            name="deposit_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="contractdetails",
            name="deposit_payment_method",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="contractdetails",
            name="floor_location",
            field=models.CharField(
                blank=True,
                help_text="E.g., links, mitte, rechts",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="contractdetails",
            name="has_inclusive_utilities",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="contractdetails",
            name="has_indexed_rent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="contractdetails",
            name="has_shared_drying_room",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="contractdetails",
            name="has_shared_garden",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="contractdetails",
            name="has_shared_laundry",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="contractdetails",
            name="has_stepped_rent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="contractdetails",
            name="heating_prepayment",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="contractdetails",
            name="is_unlimited_contract",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="contractdetails",
            name="landlord_bank_details",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contractdetails",
            name="num_apartment_keys",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contractdetails",
            name="num_building_keys",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contractdetails",
            name="num_mailbox_keys",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contractdetails",
            name="pets_allowed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="contractdetails",
            name="property_type",
            field=models.CharField(
                blank=True,
                help_text="E.g., Eigentumswohnung, Mietwohnung, etc.",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="contractdetails",
            name="quiet_hours",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="contractdetails",
            name="rent_adjustment_terms",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contractdetails",
            name="rent_due_date",
            field=models.IntegerField(
                blank=True, help_text="Day of month when rent is due", null=True
            ),
        ),
        migrations.AddField(
            model_name="contractdetails",
            name="small_repairs_cost_limit",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Cost limit for small repairs in EUR",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="contractdetails",
            name="small_repairs_responsibility",
            field=models.CharField(
                blank=True,
                help_text="Who is responsible for Kleinreparaturen",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="contractdetails",
            name="subletting_allowed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="contractdetails",
            name="subletting_requires_permission",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="contractdetails",
            name="termination_notice_period_landlord",
            field=models.IntegerField(
                blank=True, help_text="Notice period in months for landlord", null=True
            ),
        ),
        migrations.AddField(
            model_name="contractdetails",
            name="termination_notice_period_tenant",
            field=models.IntegerField(
                blank=True, help_text="Notice period in months for tenant", null=True
            ),
        ),
        migrations.AddField(
            model_name="contractdetails",
            name="utility_billing_method",
            field=models.CharField(
                blank=True,
                help_text="E.g., consumption-based, by living space",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="contractdetails",
            name="utility_prepayment",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
