# Generated by Django 5.1.6 on 2025-03-06 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "contract_analysis",
            "0005_remove_contractdetails_additional_clauses_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="contractdetails",
            old_name="address",
            new_name="street",
        ),
        migrations.DeleteModel(
            name="Paragraph",
        ),
    ]
