# Generated by Django 5.1.6 on 2025-03-06 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contract_analysis", "0006_rename_address_contractdetails_street_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contractdetails",
            name="contract_text",
        ),
    ]
