# Generated by Django 5.1.6 on 2025-03-06 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contract_analysis", "0007_remove_contractdetails_contract_text"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContractText",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(blank=True, null=True)),
                ("friendly_text", models.TextField(blank=True, null=True)),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="text",
                        to="contract_analysis.contract",
                    ),
                ),
            ],
        ),
    ]
