# Generated by Django 5.1.6 on 2025-03-07 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contract_analysis", "0008_contracttext"),
    ]

    operations = [
        migrations.AddField(
            model_name="contractdetails",
            name="neighborhood",
            field=models.TextField(blank=True, null=True),
        ),
    ]
