# Generated by Django 5.1.6 on 2025-03-20 07:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Analysis",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("is_extended", models.BooleanField(default=False)),
                (
                    "source_entitlement",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="analyses",
                        to="accounts.entitlement",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analyses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, default="Mietervertrag", max_length=255
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploaded", "Uploaded"),
                            ("processing", "Processing"),
                            ("analyzed", "Analyzed"),
                        ],
                        default="uploaded",
                        max_length=20,
                    ),
                ),
                ("archived", models.BooleanField(default=False)),
                ("archived_date", models.DateTimeField(blank=True, null=True)),
                ("retention_days", models.IntegerField(default=365)),
                ("scheduled_deletion_date", models.DateField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ContractDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contract_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("unlimited", "Unbefristeter Mietvertrag"),
                            ("limited", "Befristeter Mietvertrag"),
                            ("sublease", "Untermietvertrag"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("street", models.CharField(blank=True, max_length=255, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("postal_code", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "property_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("apartment", "Wohnung"),
                            ("house", "Haus"),
                            ("room", "Zimmer"),
                            ("commercial", "Gewerbe"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "number_of_rooms",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=3, null=True
                    ),
                ),
                (
                    "living_space",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="In square meters",
                        max_digits=8,
                        null=True,
                    ),
                ),
                ("kitchen", models.BooleanField(default=False)),
                ("bathroom", models.BooleanField(default=False)),
                ("separate_wc", models.BooleanField(default=False)),
                ("balcony_or_terrace", models.BooleanField(default=False)),
                ("garden", models.BooleanField(default=False)),
                ("garage_or_parking", models.BooleanField(default=False)),
                ("elevator", models.BooleanField(default=False)),
                (
                    "basic_rent",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "operating_costs",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "heating_costs",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "garage_costs",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "other_costs",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "operating_costs_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("fixed", "Festbetrag"),
                            ("advance", "Vorauszahlung mit Abrechnung"),
                            ("allocation", "Pauschale ohne Abrechnung"),
                        ],
                        default="advance",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "heating_costs_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("fixed", "Festbetrag"),
                            ("advance", "Vorauszahlung mit Abrechnung"),
                            ("allocation", "Pauschale ohne Abrechnung"),
                        ],
                        default="advance",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "deposit_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "termination_notice_tenant",
                    models.PositiveIntegerField(
                        blank=True,
                        default=3,
                        help_text="Notice period in months for tenant",
                        null=True,
                    ),
                ),
                (
                    "termination_notice_landlord",
                    models.PositiveIntegerField(
                        blank=True,
                        default=3,
                        help_text="Notice period in months for landlord",
                        null=True,
                    ),
                ),
                (
                    "cosmetic_repairs",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("tenant", "Mieter"),
                            ("landlord", "Vermieter"),
                            ("shared", "Geteilt"),
                        ],
                        default="tenant",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "small_repairs",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("tenant", "Mieter"),
                            ("landlord", "Vermieter"),
                            ("shared", "Geteilt"),
                        ],
                        default="tenant",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "small_repairs_limit",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "pets_allowed",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "subletting_allowed",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                ("quiet_hours_start", models.TimeField(blank=True, null=True)),
                ("quiet_hours_end", models.TimeField(blank=True, null=True)),
                (
                    "renovation_interval_years",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "has_stepped_rent",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "has_indexed_rent",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                ("neighborhood_analysis", models.TextField(blank=True, null=True)),
                ("full_contract_text", models.TextField(blank=True, null=True)),
                ("simplified_paragraphs", models.TextField(blank=True, null=True)),
                (
                    "contract",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details",
                        to="contract_analysis.contract",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rental Contract",
                "verbose_name_plural": "Rental Contracts",
            },
        ),
        migrations.CreateModel(
            name="ContractFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_name", models.CharField(blank=True, default="", max_length=255)),
                ("file_content", models.BinaryField(null=True)),
                ("file_type", models.CharField(default="image/png", max_length=20)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("file_size", models.IntegerField(default=0)),
                ("encrypted_content", models.BinaryField(null=True)),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="contract_analysis.contract",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="contract",
            index=models.Index(
                fields=["user", "status"], name="contract_an_user_id_26593c_idx"
            ),
        ),
    ]
