# Generated by Django 5.1.6 on 2025-03-07 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contract_analysis", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contractdetails",
            options={
                "verbose_name": "Rental Contract",
                "verbose_name_plural": "Rental Contracts",
            },
        ),
        migrations.RenameField(
            model_name="contractdetails",
            old_name="garage_or_parking_space",
            new_name="garage_or_parking",
        ),
        migrations.RemoveField(
            model_name="contractdetails",
            name="contract_date",
        ),
        migrations.RemoveField(
            model_name="contractdetails",
            name="cosmetic_repairs_responsibility",
        ),
        migrations.RemoveField(
            model_name="contractdetails",
            name="country",
        ),
        migrations.RemoveField(
            model_name="contractdetails",
            name="deposit_payment_method",
        ),
        migrations.RemoveField(
            model_name="contractdetails",
            name="energy_class",
        ),
        migrations.RemoveField(
            model_name="contractdetails",
            name="energy_consumption",
        ),
        migrations.RemoveField(
            model_name="contractdetails",
            name="garage_number",
        ),
        migrations.RemoveField(
            model_name="contractdetails",
            name="has_shared_garden",
        ),
        migrations.RemoveField(
            model_name="contractdetails",
            name="has_shared_laundry",
        ),
        migrations.RemoveField(
            model_name="contractdetails",
            name="has_shared_washing_machine",
        ),
        migrations.RemoveField(
            model_name="contractdetails",
            name="landlord_account_holder",
        ),
        migrations.RemoveField(
            model_name="contractdetails",
            name="landlord_bank_name",
        ),
        migrations.RemoveField(
            model_name="contractdetails",
            name="landlord_iban",
        ),
        migrations.RemoveField(
            model_name="contractdetails",
            name="num_apartment_keys",
        ),
        migrations.RemoveField(
            model_name="contractdetails",
            name="num_building_keys",
        ),
        migrations.RemoveField(
            model_name="contractdetails",
            name="num_garage_keys",
        ),
        migrations.RemoveField(
            model_name="contractdetails",
            name="num_mailbox_keys",
        ),
        migrations.RemoveField(
            model_name="contractdetails",
            name="renovation_interval_walls",
        ),
        migrations.RemoveField(
            model_name="contractdetails",
            name="renovation_interval_woodwork",
        ),
        migrations.RemoveField(
            model_name="contractdetails",
            name="rent_due_date",
        ),
        migrations.RemoveField(
            model_name="contractdetails",
            name="signing_location",
        ),
        migrations.RemoveField(
            model_name="contractdetails",
            name="small_repairs_cost_limit",
        ),
        migrations.RemoveField(
            model_name="contractdetails",
            name="small_repairs_responsibility",
        ),
        migrations.RemoveField(
            model_name="contractdetails",
            name="subletting_requires_permission",
        ),
        migrations.RemoveField(
            model_name="contractdetails",
            name="termination_notice_period_landlord",
        ),
        migrations.RemoveField(
            model_name="contractdetails",
            name="termination_notice_period_tenant",
        ),
        migrations.RemoveField(
            model_name="contractdetails",
            name="year_of_construction",
        ),
        migrations.AddField(
            model_name="contractdetails",
            name="basic_rent",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="contractdetails",
            name="cosmetic_repairs",
            field=models.CharField(
                blank=True,
                choices=[
                    ("tenant", "Mieter"),
                    ("landlord", "Vermieter"),
                    ("shared", "Geteilt"),
                ],
                default="tenant",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="contractdetails",
            name="garage_costs",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="contractdetails",
            name="has_indexed_rent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="contractdetails",
            name="has_stepped_rent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="contractdetails",
            name="heating_costs",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="contractdetails",
            name="heating_costs_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("fixed", "Festbetrag"),
                    ("advance", "Vorauszahlung mit Abrechnung"),
                    ("allocation", "Pauschale ohne Abrechnung"),
                ],
                default="advance",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="contractdetails",
            name="operating_costs",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="contractdetails",
            name="operating_costs_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("fixed", "Festbetrag"),
                    ("advance", "Vorauszahlung mit Abrechnung"),
                    ("allocation", "Pauschale ohne Abrechnung"),
                ],
                default="advance",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="contractdetails",
            name="other_costs",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="contractdetails",
            name="renovation_interval_years",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contractdetails",
            name="small_repairs",
            field=models.CharField(
                blank=True,
                choices=[
                    ("tenant", "Mieter"),
                    ("landlord", "Vermieter"),
                    ("shared", "Geteilt"),
                ],
                default="tenant",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="contractdetails",
            name="small_repairs_limit",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AddField(
            model_name="contractdetails",
            name="termination_notice_landlord",
            field=models.PositiveIntegerField(
                blank=True,
                default=3,
                help_text="Notice period in months for landlord",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="contractdetails",
            name="termination_notice_tenant",
            field=models.PositiveIntegerField(
                blank=True,
                default=3,
                help_text="Notice period in months for tenant",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="contractdetails",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="contractdetails",
            name="contract",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="details",
                to="contract_analysis.contract",
            ),
        ),
        migrations.AlterField(
            model_name="contractdetails",
            name="contract_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("unlimited", "Unbefristeter Mietvertrag"),
                    ("limited", "Befristeter Mietvertrag"),
                    ("sublease", "Untermietvertrag"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="contractdetails",
            name="deposit_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="contractdetails",
            name="living_space",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="In square meters",
                max_digits=8,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="contractdetails",
            name="number_of_rooms",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=3, null=True
            ),
        ),
        migrations.AlterField(
            model_name="contractdetails",
            name="postal_code",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="contractdetails",
            name="property_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("apartment", "Wohnung"),
                    ("house", "Haus"),
                    ("room", "Zimmer"),
                    ("commercial", "Gewerbe"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="contractdetails",
            name="quiet_hours_end",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="contractdetails",
            name="quiet_hours_start",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="contractdetails",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="contractdetails",
            name="street",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
