# Generated by Django 5.1.6 on 2025-03-14 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contract_analysis", "0003_contractdetails_neighborhood_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contractdetails",
            name="has_indexed_rent",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="contractdetails",
            name="has_stepped_rent",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="contractdetails",
            name="pets_allowed",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="contractdetails",
            name="subletting_allowed",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
