# Generated by Django 5.1.6 on 2025-03-17 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contract_analysis", "0004_alter_contractdetails_has_indexed_rent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contractdetails",
            name="simplified_paragraphs",
            field=models.TextField(blank=True, null=True),
        ),
    ]
