# Generated by Django 5.1.6 on 2025-03-18 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contract_analysis", "0005_contractdetails_simplified_paragraphs"),
    ]

    operations = [
        migrations.AddField(
            model_name="contractdetails",
            name="full_contract_text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
