# Generated by Django 5.1.6 on 2025-03-19 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contract_analysis", "0006_contractdetails_full_contract_text"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contractdetails",
            old_name="neighborhood_description",
            new_name="neighborhood_analysis",
        ),
    ]
